server:
  port: 8081
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.ahui: TRACE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_sale_managerment?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: peng1989127
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    bcrypt:
      strength: 12  # 计算强度（4-31，默认10）
jwt:
  secret: "dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLXRlc3Rpbmc=" # Base64编码示例
  expiration: 86400
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志